apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: fissure/redis:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 7000
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: redis
spec:
  type: NodePort
  ports:
    - port: 7000 # Port to expose internally in cluster
      # For k3s deployment, the node port is exposed using docker
      # which maps back to 7000 using command
      # k3d create --publish 8082:32700@k3d-k3s-default-worker-0 --workers 1
      nodePort: 32700 # Port to expose outside k8s cluster
      targetPort: 7000 # Port that containers listen on
      protocol: TCP
  selector:
    app: redis
