apiVersion: apps/v1
kind: Deployment
metadata:
  name: mantis-worker
spec:
  replicas: 10
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: fissure/py:latest
          imagePullPolicy: Always
          command:
            [
              "mantis",
              "consume",
              "--redis-ip",
              "redis-service",
              "--redis-port",
              "7000",
            ]
          resources:
            requests:
              cpu: 500m
              memory: 0.5Gi
            limits:
              cpu: 2000m
              memory: 0.5Gi
